export class Documents {
  id: number;
  folio: string;
  tome: string;
  year: number;
  publicRegistryEntryDate: string;
  publicRegistryExitDate: string;
  documentTypeOther: string;
  electronicFolio: string;
  fileNumber: string;
  moneyLaundering: number;
  moneyLaunderingExpirationDate: string;
  clientId: number;
  documentStatusId: number;
  documentTypeId: number;
  operations: [];
  groups: { name: string }[];
  grantors: [];
  marginalNotes: number;
  personalities: [];
  documentRegistry: number;
  publicRegistryPatent: number;
  identifications: number;
  property: string;
  attachments: [];
  documentAttachments: [];
  closureUsers: [];
  entryUsers: [];
  documentComments: [];
  documentProperties: [];
  documentFiles: [];
}
